GET http://localhost:3001/api/xxxx HTTP/1.1
Content-type: application/json; charset=utf-8

###
POST http://localhost:3001/api/fakeProduct HTTP/1.1
Content-type: application/json; charset=utf-8

{
    "courseId": "65040d4666dc031798504fd8",
    "hasState": false,
    "appName": "toefl",
    "isFAQ": false,
    "hasSkillTable": true
}